import type { CrossCheck } from "./types";

/**
 * Every automated cross-check / flag the extractor runs. Ported from
 * docs/EXTRACTOR-COMPLETE-REFERENCE.md Part 9. `code` is the named check ("C9",
 * "H3") or "" for the unnamed ones.
 */
export const CROSS_CHECKS: CrossCheck[] = [
  {
    id: "c3",
    code: "C3",
    name: "structure ↔ dwellings-wide",
    trigger: "SINGLE/APARTMENT with dwellingsWide≠1, or PAIR/TERRACE with <2.",
    effect: "warnings.structureDwellingsMismatch — this pair drives the frontage division, so a contradiction mis-prices the perimeter.",
    warningKey: "structureDwellingsMismatch",
    status: "confirmed",
  },
  {
    id: "c5",
    code: "C5",
    name: "storey ladder = deltas",
    trigger: "Direct vs summed-ladder height gap > 0.15 m even when the lift count agrees.",
    effect: "A note in the height derivation trail — one of the two reads may be slightly off.",
    warningKey: "heightDerivation",
    status: "confirmed",
  },
  {
    id: "c7",
    code: "C7",
    name: "apex reasoning order",
    trigger: "The schema orders faceRoof → apexReason → apexCount.",
    effect: "The reasoning is committed BEFORE the number, so it informs the count rather than rationalising it.",
    status: "confirmed",
  },
  {
    id: "c8",
    code: "C8",
    name: "rendered-but-undimensioned",
    trigger: "A rendered face with no renderLengthM.",
    effect: "warnings.renderedNotDimensioned — so render isn't silently dropped.",
    warningKey: "renderedNotDimensioned",
    status: "confirmed",
  },
  {
    id: "c9",
    code: "C9",
    name: "wall symmetry",
    trigger: "front≈rear and gable_left≈gable_right; a >10% mismatch.",
    effect: "warnings.wallAsymmetry — flags a likely wall-role swap or misread.",
    warningKey: "wallAsymmetry",
    status: "confirmed",
  },
  {
    id: "c11",
    code: "C11",
    name: "Birdcage internal-vs-derived cross-check",
    trigger: "A printed internal span AND an overall−walls derivation both exist; they should agree within 5%.",
    effect: "Within tolerance → high (medium if a wall was assumed symmetric); diverge → low + flag (in the birdcage derivation).",
    warningKey: "birdcageDerivation",
    status: "confirmed",
  },
  {
    id: "h3",
    code: "H3",
    name: "height lift-count",
    trigger: "The direct read and the storey ladder give a different ceil(h ÷ 1.5).",
    effect: "Height confidence → low + flag (only the lift count matters, not a fixed mm gap).",
    warningKey: "heightDerivation",
    status: "confirmed",
  },
  {
    id: "a2",
    code: "A2",
    name: "gablet / half-hip / chimney-on-gable",
    trigger: "Brickwork rises to a point on an unusual face.",
    effect: "Count the apex normally (proposed — ⚠️ confirm with Colin).",
    status: "open",
  },
  {
    id: "w2",
    code: "W2",
    name: "overhang-only wall",
    trigger: "Only the roof/overhang dimension is legible for a wall.",
    effect: "Store it low-confidence as-is + flag; never subtract an overhang (⚠️ confirm).",
    status: "open",
  },
  {
    id: "dimVerify",
    code: "",
    name: "dimension verification",
    trigger: "A cited sourceDimension isn't found in the PDF text layer.",
    effect: "Confidence capped to low + warnings.unverifiedDimensions (catches misreads/hallucinations).",
    warningKey: "unverifiedDimensions",
    status: "confirmed",
  },
  {
    id: "wallOffElevation",
    code: "",
    name: "wall off elevation",
    trigger: "A wall cited on an ELEVATION page (and not also on a plan).",
    effect: "Capped + warnings.wallReadOffElevation (roof-overhang risk).",
    warningKey: "wallReadOffElevation",
    status: "confirmed",
  },
  {
    id: "apexContradiction",
    code: "",
    name: "apex contradiction",
    trigger: "A face marked HIPPED that still reports an apex.",
    effect: "warnings.apexContradictions; a hipped overall roof forces apex 0.",
    warningKey: "apexContradictions",
    status: "confirmed",
  },
  {
    id: "roomInRoofMismatch",
    code: "",
    name: "room-in-roof ↔ storeys",
    trigger: "storeys=2.5 with roomInRoof=false, or roomInRoof=true on a whole-number storey.",
    effect: "warnings.roomInRoofMismatch.",
    warningKey: "roomInRoofMismatch",
    status: "confirmed",
  },
];
