import type { CrossCheck } from "./types";

/**
 * Every automated cross-check / flag the extractor runs. Ported from
 * docs/EXTRACTOR-COMPLETE-REFERENCE.md Part 9. `code` is the named check ("C9",
 * "H3") or "" for the unnamed ones.
 */
export const CROSS_CHECKS: CrossCheck[] = [
  {
    id: "c3",
    code: "C3",
    name: "structure ↔ dwellings-wide",
    trigger: "DETACHED/APARTMENT with dwellingsWide≠1, or a frontage spanning more houses than the building has (pair > 2, three-block > 3). A PAIR read as 1 is VALID (a sheet that draws one house) — the old '<2' rule pushed the model into halving one-house frontages.",
    effect: "warnings.structureDwellingsMismatch — this pair drives the frontage division, so a contradiction mis-prices the perimeter.",
    warningKey: "structureDwellingsMismatch",
    status: "confirmed",
  },
  {
    id: "c5",
    code: "C5",
    name: "storey ladder = deltas",
    trigger: "Direct vs summed-ladder height gap > 0.15 m even when the lift count agrees.",
    effect: "A note in the height derivation trail — one of the two reads may be slightly off.",
    warningKey: "heightDerivation",
    status: "confirmed",
  },
  {
    id: "c7",
    code: "C7",
    name: "apex reasoning order",
    trigger: "The schema orders faceRoof → apexReason → apexCount.",
    effect: "The reasoning is committed BEFORE the number, so it informs the count rather than rationalising it.",
    status: "confirmed",
  },
  {
    id: "c8",
    code: "C8",
    name: "rendered-but-undimensioned",
    trigger: "A rendered face with no renderLengthM.",
    effect: "warnings.renderedNotDimensioned — so render isn't silently dropped.",
    warningKey: "renderedNotDimensioned",
    status: "confirmed",
  },
  {
    id: "c9",
    code: "C9",
    name: "wall symmetry",
    trigger: "front≈rear and gable_left≈gable_right; a >10% mismatch.",
    effect: "warnings.wallAsymmetry — flags a likely wall-role swap or misread.",
    warningKey: "wallAsymmetry",
    status: "confirmed",
  },
  {
    id: "c11",
    code: "C11",
    name: "Birdcage internal-vs-derived cross-check",
    trigger: "A printed internal span AND an overall−walls derivation both exist; they should agree within 5%.",
    effect: "Within tolerance → high (medium if a wall was assumed symmetric); diverge → low + flag (in the birdcage derivation).",
    warningKey: "birdcageDerivation",
    status: "confirmed",
  },
  {
    id: "c12",
    code: "C12",
    name: "Corner ↔ birdcage-shape consistency",
    trigger: "cornerCount > 4 (non-rectangular) should coincide with a birdcage split into >1 rectangle — and vice-versa.",
    effect: "Mismatch → flag (a stepped footprint counted as one rectangle, or a split birdcage with only 4 corners).",
    warningKey: "cornerBirdcageMismatch",
    status: "confirmed",
  },
  {
    id: "c13",
    code: "C13",
    name: "Per-house birdcage width vs shared frontage",
    trigger: "Pair/terrace: a birdcage rectangle's width is close to the FULL frontage instead of one house (≈ frontage ÷ dwellings).",
    effect: "Flag the whole-pair over-read (report one house's width, not the pair).",
    warningKey: "pairBirdcageWidth",
    status: "confirmed",
  },
  {
    id: "frontage-frame",
    code: "",
    name: "Frontage frame (physical minimum + birdcage cross-check)",
    trigger: "resolveFrontage: front ÷ dwellingsWide < 3 m (no house is that narrow) → the length is ONE house, not divided. Separately, one house's frontage narrower than its own internal birdcage width, within 0.15 m of it (an internal dim read as the wall), or >1.2 m wider (single-rectangle floor).",
    effect: "The divisor is corrected ONLY on the physical minimum; the birdcage disagreement is a Review flag, never a correction (a whole-pair birdcage looks identical to a correct one-house frontage). warnings.frontageResolution records the read, the applied divisor and why.",
    warningKey: "frontageResolution",
    status: "confirmed",
  },
  {
    id: "wall-roles",
    code: "",
    name: "Wall roles follow the party wall",
    trigger: "A front or rear wall read as the PARTY wall, with no side wall marked party (Miller Millfield: an 11.138 m side read as the front).",
    effect: "normalizeWallRoles renames the two axes (a party wall is always a side wall) and flags it — warnings.wallRolesSwapped. Never on shape alone: 4 of 73 attached bank types are genuinely wider than deep, so 'front wider than the side' stays a flag.",
    warningKey: "wallRolesSwapped",
    status: "confirmed",
  },
  {
    id: "h3",
    code: "H3",
    name: "height lift-count",
    trigger: "The direct read and the storey ladder give a different ceil(h ÷ 1.5).",
    effect: "Height confidence → low + flag (only the lift count matters, not a fixed mm gap).",
    warningKey: "heightDerivation",
    status: "confirmed",
  },
  {
    id: "a2",
    code: "A2",
    name: "gablet / half-hip / chimney-on-gable",
    trigger: "Brickwork rises to a point on an unusual face.",
    effect: "Count the apex normally (proposed — ⚠️ confirm with Colin).",
    status: "open",
  },
  {
    id: "w2",
    code: "W2",
    name: "overhang-only wall",
    trigger: "Only the roof/overhang dimension is legible for a wall.",
    effect: "Store it low-confidence as-is + flag; never subtract an overhang (⚠️ confirm).",
    status: "open",
  },
  {
    id: "dimVerify",
    code: "",
    name: "dimension verification",
    trigger: "A cited sourceDimension isn't found in the PDF text layer.",
    effect: "Confidence capped to low + warnings.unverifiedDimensions (catches misreads/hallucinations).",
    warningKey: "unverifiedDimensions",
    status: "confirmed",
  },
  {
    id: "wallOffElevation",
    code: "",
    name: "wall off elevation",
    trigger: "A wall cited on an ELEVATION page (and not also on a plan).",
    effect: "Capped + warnings.wallReadOffElevation (roof-overhang risk).",
    warningKey: "wallReadOffElevation",
    status: "confirmed",
  },
  {
    id: "apexContradiction",
    code: "",
    name: "apex contradiction",
    trigger: "A face marked HIPPED that still reports an apex.",
    effect: "warnings.apexContradictions; a hipped overall roof forces apex 0.",
    warningKey: "apexContradictions",
    status: "confirmed",
  },
  {
    id: "roomInRoofMismatch",
    code: "",
    name: "room-in-roof ↔ storeys",
    trigger: "storeys=2.5 with roomInRoof=false, or roomInRoof=true on a whole-number storey.",
    effect: "warnings.roomInRoofMismatch.",
    warningKey: "roomInRoofMismatch",
    status: "confirmed",
  },
];
